name: ccda_to_omop file comparisons
run-name: ${{ github.actor }} is comparing output files on master
on: [push, workflow_dispatch]
jobs:
    Run-file-comparisons:
        runs-on: ubuntu-latest
        steps:
          - name: Check out repository code
            uses: actions/checkout@v4
            with:
              ref: master
          - name: Install packages
            run: |
                pip install -r requirements.txt
          - name: run conversion
            run: |
                bin/process.sh
          - name: run comparison
            run: |
                bin/compare_correct.sh
