name: ccda_to_omop Unit Tests
run-name: ${{ github.actor }} is testing ccda_to_omop unit tests
on: [push, workflow_dispatch]
jobs:
    Run-unit-tests:
        runs-on: ubuntu-latest
        steps:
          - name: Check out repository code
            uses: actions/checkout@v4
            with:
              ref: dev
          - name: Install packages
            run: |
                pip install -r requirements.txt
          - name: get the concept map file
            run: |
              wget https://media.githubusercontent.com/media/croeder/CCDA_OMOP_Private/refs/heads/main/map.csv?token=AAA5CJJL5FBY6JPRDPD6TBTJ22HSQ
              mv map.csv resources
          - name: run unit tests
            run: |
                bin/run_unittests.sh
