name: ccda_to_omop Unit Tests
run-name: ${{ github.actor }} is testing ccda_to_omop unit tests
on: [push, workflow_dispatch]
jobs:
    Run-unit-tests:
        runs-on: ubuntu-latest
        steps:
          - name: Check out repository code
            uses: actions/checkout@v4
          - name: Set up Python
            uses: actions/setup-python@v5
            with:
              python-version: '3.x'
          - name: Install packages
            run: pip install -r requirements.txt
          - name: get the concept map file
            run: |
              wget --header="Authorization: token ${{ secrets.CROEDER_CCDA_PRIVATE_ACCESS_TOKEN }}" \
                   --header="Accept: */*" \
                   -O resources/map.csv \
                   "https://media.githubusercontent.com/media/croeder/CCDA_OMOP_Private/refs/heads/main/map.csv"
          - name: run unit tests
            run: bin/run_unittests.sh
